[project]
name = 'Transparent-Public-Utility-Subsidy-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.benefit-calculation]
path = 'contracts/benefit-calculation.clar'
clarity_version = 2
epoch = 2.5

[contracts.recipient-verification]
path = 'contracts/recipient-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-monitoring]
path = 'contracts/usage-monitoring.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
